=== PromiseCatch/MineCity/Core/src/main/resources/assets/minecity/commands.dtd
<!ELEMENT minecity-commands (groups, commands)>
<!ELEMENT groups (group+)>
<!ELEMENT group (desc)>
<!ELEMENT commands (command+)>
<!ELEMENT command (desc)>
<!ELEMENT desc (#PCDATA)>

<!ATTLIST minecity-commands
        modified (true|false) "true"
        add-missing (true|false) "false">

<!ATTLIST group
        id CDATA #REQUIRED
        cmd CDATA #REQUIRED
        parent CDATA #IMPLIED>

<!ENTITY % NatureManageCommands "nature.rename">
<!ENTITY % NatureDenyCommands "nature.deny.enter|nature.deny.click|nature.deny.pickup|nature.deny.harvest|nature.deny.open|nature.deny.pvp|nature.deny.pvc|nature.deny.modify|nature.deny.vehicle|nature.deny.ride">
<!ENTITY % NatureAllowCommands "nature.allow.enter|nature.allow.click|nature.allow.pickup|nature.allow.harvest|nature.allow.open|nature.allow.pvp|nature.allow.pvc|nature.allow.modify|nature.allow.vehicle|nature.allow.ride">
<!ENTITY % NaturePermListCommands "nature.perms.enter|nature.perms.click|nature.perms.pickup|nature.perms.harvest|nature.perms.open|nature.perms.pvp|nature.perms.pvc|nature.perms.modify|nature.perms.vehicle|nature.perms.ride|nature.perms">
<!ENTITY % CityManageCommands "city.create|city.claim|city.disclaim|city.spawn|city.rename|city.transfer|city.setspawn|city.map|city.delete|city.info|city.list|city.sell|city.abort|city.abort.sell|city.buy|auto.claim">
<!ENTITY % CityDenyCommands "city.deny.enter|city.deny.click|city.deny.pickup|city.deny.harvest|city.deny.open|city.deny.pvp|city.deny.pvc|city.deny.modify|city.deny.vehicle|city.deny.ride">
<!ENTITY % CityAllowCommands "city.allow.enter|city.allow.click|city.allow.pickup|city.allow.harvest|city.allow.open|city.allow.pvp|city.allow.pvc|city.allow.modify|city.allow.vehicle|city.allow.ride">
<!ENTITY % CityResetCommands "city.clear.enter|city.clear.click|city.clear.pickup|city.clear.harvest|city.clear.open|city.clear.pvp|city.clear.pvc|city.clear.modify|city.clear.vehicle|city.clear.ride">
<!ENTITY % CityDenyAllCommands "city.deny.all.enter|city.deny.all.click|city.deny.all.pickup|city.deny.all.harvest|city.deny.all.open|city.deny.all.pvp|city.deny.all.pvc|city.deny.all.modify|city.deny.all.vehicle|city.deny.all.ride">
<!ENTITY % CityAllowAllCommands "city.allow.all.enter|city.allow.all.click|city.allow.all.pickup|city.allow.all.harvest|city.allow.all.open|city.allow.all.pvp|city.allow.all.pvc|city.allow.all.modify|city.allow.all.vehicle|city.allow.all.ride">
<!ENTITY % CityResetAllCommands "city.clear.all.enter|city.clear.all.click|city.clear.all.pickup|city.clear.all.harvest|city.clear.all.open|city.clear.all.pvp|city.clear.all.pvc|city.clear.all.modify|city.clear.all.vehicle|city.clear.all.ride">
<!ENTITY % CityPermListCommands "city.perms.enter|city.perms.click|city.perms.pickup|city.perms.harvest|city.perms.open|city.perms.pvp|city.perms.pvc|city.perms.modify|city.perms.vehicle|city.perms.ride|city.perms">
<!ENTITY % PlotManageCommands "plot.create|plot.rename|plot.return|plot.transfer|plot.delete|plot.info|plot.readjust|plot.list|plot.sell|plot.cancel.sell|plot.buy">
<!ENTITY % PlotDenyCommands "plot.deny.enter|plot.deny.click|plot.deny.pickup|plot.deny.harvest|plot.deny.open|plot.deny.pvp|plot.deny.pvc|plot.deny.modify|plot.deny.vehicle|plot.deny.ride">
<!ENTITY % PlotAllowCommands "plot.allow.enter|plot.allow.click|plot.allow.pickup|plot.allow.harvest|plot.allow.open|plot.allow.pvp|plot.allow.pvc|plot.allow.modify|plot.allow.vehicle|plot.allow.ride">
<!ENTITY % PlotResetCommands "plot.clear.enter|plot.clear.click|plot.clear.pickup|plot.clear.harvest|plot.clear.open|plot.clear.pvp|plot.clear.pvc|plot.clear.modify|plot.clear.vehicle|plot.clear.ride">
<!ENTITY % PlotDenyAllCommands "plot.deny.all.enter|plot.deny.all.click|plot.deny.all.pickup|plot.deny.all.harvest|plot.deny.all.open|plot.deny.all.pvp|plot.deny.all.pvc|plot.deny.all.modify|plot.deny.all.vehicle|plot.deny.all.ride">
<!ENTITY % PlotAllowAllCommands "plot.allow.all.enter|plot.allow.all.click|plot.allow.all.pickup|plot.allow.all.harvest|plot.allow.all.open|plot.allow.all.pvp|plot.allow.all.pvc|plot.allow.all.modify|plot.allow.all.vehicle|plot.allow.all.ride">
<!ENTITY % PlotResetAllCommands "plot.clear.all.enter|plot.clear.all.click|plot.clear.all.pickup|plot.clear.all.harvest|plot.clear.all.open|plot.clear.all.pvp|plot.clear.all.pvc|plot.clear.all.modify|plot.clear.all.vehicle|plot.clear.all.ride">
<!ENTITY % PlotPermListCommands "plot.perms.enter|plot.perms.click|plot.perms.pickup|plot.perms.harvest|plot.perms.open|plot.perms.pvp|plot.perms.pvc|plot.perms.modify|plot.perms.vehicle|plot.perms.ride|plot.perms">
<!ENTITY % GroupCommands "group.create|group.add|group.remove|group.list|group.info|group.delete|group.manager.add|group.manager.remove">
<!ENTITY % GeneralCommands "confirm|help|configs.reload|reactive.reload|admin|dump.blocks">

<!ENTITY % NaturePermCommands "%NatureAllowCommands;|%NatureDenyCommands;|%NaturePermListCommands;">
<!ENTITY % PlotPermCommands "%PlotAllowCommands;|%PlotDenyCommands;|%PlotAllowAllCommands;|%PlotDenyAllCommands;|%PlotPermListCommands;|%CityResetCommands;|%CityResetAllCommands;">
<!ENTITY % CityPermCommands "%CityAllowCommands;|%CityDenyCommands;|%CityAllowAllCommands;|%CityDenyAllCommands;|%CityPermListCommands;|%PlotResetCommands;|%PlotResetAllCommands;">
<!ENTITY % PlotCommands "%PlotManageCommands;|%PlotPermCommands;">
<!ENTITY % CityCommands "%CityManageCommands;|%CityPermCommands;">
<!ENTITY % NatureCommands "%NatureManageCommands;|%NaturePermCommands;">
<!ENTITY % Commands "%NatureCommands;|%CityCommands;|%GroupCommands;|%GeneralCommands;|%PlotCommands;">

<!ATTLIST command
        id (%Commands;) #REQUIRED
        cmd CDATA #REQUIRED
        parent CDATA #IMPLIED>

=== PromiseCatch/MineCity/Core/src/main/resources/assets/minecity/commands-en.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE minecity-commands SYSTEM "https://raw.githubusercontent.com/GameModsBR/MineCity/master/Core/src/main/resources/assets/minecity/commands.dtd">
<minecity-commands modified="false" add-missing="true">
    <groups>
        <group id="root" cmd="minecity,mc">
            <desc>All MineCity commands</desc>
        </group>
        <group id="dump" parent="root" cmd="dump">
            <desc>Dumps information about the system to the filesystem</desc>
        </group>
        <group id="city" parent=",root" cmd="city,town,c,t">
            <desc>All city related commands</desc>
        </group>
        <group id="group" parent=",root,city" cmd="group">
            <desc>All group related commands</desc>
        </group>
        <group id="group.manager" parent="group" cmd="manager,managers">
            <desc>All group managers related commands</desc>
        </group>
        <group id="plot" parent=",city,root" cmd="plot">
            <desc>All plot related commands</desc>
        </group>
        <group id="nature" parent=",root" cmd="nature,world">
            <desc>All nature related commands</desc>
        </group>
        <group id="nature.allow" parent="nature" cmd="allow">
            <desc>Gives permission</desc>
        </group>
        <group id="nature.deny" parent="nature" cmd="deny">
            <desc>Revokes permission</desc>
        </group>
        <group id="nature.check" parent="nature" cmd="check">
            <desc>Shows details about permissions</desc>
        </group>
        <group id="city.allow" parent="city" cmd="allow">
            <desc>Gives permission</desc>
        </group>
        <group id="city.deny" parent="city" cmd="deny">
            <desc>Revokes permission</desc>
        </group>
        <group id="city.reset" parent="city" cmd="reset">
            <desc>Removes direct permissions and restrictions</desc>
        </group>
        <group id="city.allow.all" parent="city.allow" cmd="all">
            <desc>Gives permission to everybody, including players who were directly prohibited</desc>
        </group>
        <group id="city.deny.all" parent="city.deny" cmd="all">
            <desc>Prohibits everybody, including players who were directly allowed</desc>
        </group>
        <group id="city.reset.all" parent="city.reset" cmd="all">
            <desc>Removes direct permissions from everybody</desc>
        </group>
        <group id="city.check" parent="city" cmd="check">
            <desc>Shows details about permissions</desc>
        </group>
        <group id="city.abort" parent="city" cmd="cancel,abort">
            <desc>Cancels an action related to the city</desc>
        </group>
        <group id="city.abort.sell" parent="city.abort" cmd="sell">
            <desc>Cancels a sell action</desc>
        </group>
        <group id="plot.allow" parent="plot" cmd="allow">
            <desc>Gives permission</desc>
        </group>
        <group id="plot.deny" parent="plot" cmd="deny">
            <desc>Revokes permission</desc>
        </group>
        <group id="plot.reset" parent="plot" cmd="reset">
            <desc>Removes direct permissions and restrictions</desc>
        </group>
        <group id="plot.allow.all" parent="plot.allow" cmd="all">
            <desc>Gives permission to everybody, including players who were directly prohibited</desc>
        </group>
        <group id="plot.deny.all" parent="plot.deny" cmd="all">
            <desc>Prohibits everybody, including players who were directly allowed</desc>
        </group>
        <group id="plot.reset.all" parent="plot.reset" cmd="all">
            <desc>Removes direct permissions from everybody</desc>
        </group>
        <group id="plot.check" parent="plot" cmd="check">
            <desc>Shows details about permissions</desc>
        </group>
        <group id="plot.cancel" parent="plot" cmd="cancel,abort">
            <desc>Cancels an action related to the plot</desc>
        </group>
    </groups>
    <commands>
        <!-- General -->
        <command id="confirm" parent=",city,group,root,plot" cmd="confirm">
            <desc>Confirms a dangerous action</desc>
        </command>
        <command id="help" parent="city,group,root,plot" cmd="help">
            <desc>Show information about MineCity's commands</desc>
        </command>
        <command id="configs.reload" parent="root" cmd="reload">
            <desc>Reloads the messages from the disk</desc>
        </command>
        <command id="reactive.reload" parent="root" cmd="reload-protections">
            <desc>Reloads the protections from the disk</desc>
        </command>
        <command id="admin" parent="root" cmd="admin,adm">
            <desc>Toggles your admin mode</desc>
        </command>
        <command id="dump.blocks" parent="dump" cmd="blocks">
            <desc>Dumps the block types and traits</desc>
        </command>

        <!-- Management -->
        <command id="city.info" parent="city" cmd="info">
            <desc>Shows information about the city</desc>
        </command>
        <command id="city.create" parent="city" cmd="create,new">
            <desc>Creates a city</desc>
        </command>
        <command id="city.claim" parent="city" cmd="claim,expand">
            <desc>Claims a chunk to a city</desc>
        </command>
        <command id="auto.claim" parent="city" cmd="auto-claim">
            <desc>Automatically attempts to claim a chunk when you cross the chunk boundaries</desc>
        </command>
        <command id="city.disclaim" parent="city" cmd="disclaim,unclaim">
            <desc>Disclaims a chunk from a city</desc>
        </command>
        <command id="city.spawn" parent="city" cmd="go,spawn">
            <desc>Teleport you to the city</desc>
        </command>
        <command id="city.rename" parent="city" cmd="rename">
            <desc>Changes name of the city that you are inside</desc>
        </command>
        <command id="city.transfer" parent="city" cmd="transfer">
            <desc>Transfer the city to an other player</desc>
        </command>
        <command id="city.setspawn" parent="city" cmd="setspawn">
            <desc>Changes the city's spawn location</desc>
        </command>
        <command id="city.map" parent="city" cmd="map">
            <desc>Shows a map of the cities around you</desc>
        </command>
        <command id="city.delete" parent="city" cmd="delete">
            <desc>Deletes the entire city</desc>
        </command>
        <command id="city.list" parent="city" cmd="list">
            <desc>Lists all cities</desc>
        </command>
        <command id="city.sell" parent="city" cmd="sell">
            <desc>Put a city on sale</desc>
        </command>
        <command id="city.buy" parent="city" cmd="buy,purchase">
            <desc>Purchases a city</desc>
        </command>
        <command id="city.cancel.sell" parent="city.cancel" cmd="sell">
            <desc>Cancels a city sale</desc>
        </command>

        <!-- Groups -->
        <command id="group.create" parent="group" cmd="create,new">
            <desc>Creates a new group</desc>
        </command>
        <command id="group.add" parent="group" cmd="add">
            <desc>Adds a player to a group</desc>
        </command>
        <command id="group.remove" parent="group" cmd="remove">
            <desc>Removes a player from a group</desc>
        </command>
        <command id="group.list" parent="group" cmd="list">
            <desc>Displays all city groups</desc>
        </command>
        <command id="group.info" parent="group" cmd="info">
            <desc>Displays details about a group</desc>
        </command>
        <command id="group.delete" parent="group" cmd="delete">
            <desc>Completely deletes a group from a city</desc>
        </command>
        <command id="group.manager.add" parent="group.manager" cmd="add">
            <desc>Adds a player as a group manager</desc>
        </command>
        <command id="group.manager.remove" parent="group.manager" cmd="remove">
            <desc>Demotes a player from group managers</desc>
        </command>

        <!-- Plots -->
        <command id="plot.info" parent="plot" cmd="info">
            <desc>Shows information about the plot</desc>
        </command>
        <command id="plot.readjust" parent="plot" cmd="readjust">
            <desc>Readjust the plot's shape. Can be used to completely relocate the plot.</desc>
        </command>
        <command id="plot.create" parent="plot" cmd="create,new">
            <desc>Creates a new plot</desc>
        </command>
        <command id="plot.rename" parent="plot" cmd="rename">
            <desc>Renames a plot</desc>
        </command>
        <command id="plot.return" parent="plot" cmd="return">
            <desc>Returns the ownership of a plot to the city</desc>
        </command>
        <command id="plot.transfer" parent="plot" cmd="transfer">
            <desc>Transfers the ownership of a plot to an other player</desc>
        </command>
        <command id="plot.delete" parent="plot" cmd="delete">
            <desc>Deletes a plot from a city</desc>
        </command>
        <command id="plot.list" parent="plot" cmd="list">
            <desc>Lists all plots from a city</desc>
        </command>
        <command id="plot.sell" parent="plot" cmd="sell">
            <desc>Put a plot on sale</desc>
        </command>
        <command id="plot.buy" parent="plot" cmd="buy,purchase">
            <desc>Purchases a plot</desc>
        </command>
        <command id="plot.cancel.sell" parent="plot.cancel" cmd="sell">
            <desc>Cancels a plot sale</desc>
        </command>
        
        <!-- Nature -->
        <command id="nature.rename" parent="nature" cmd="rename">
            <desc>Changes the nature's name</desc>
        </command>

        <!-- ========= Nature Permissions ========= -->
        <!-- List permissions -->
